### ISSUE TITLE
Errors in two rules terminating run

### ISSUE THREAD

**Issue by CAllex-Buckner** [snakemake-workflows/dna-seq-gatk-variant-calling#30]
Hello,

I'm getting the following errors that result in a downstream termination of the pipeline. 

```
Error in rule get_genome:
    jobid: 4
    output: resources/genome.fasta
    log: logs/get-genome.log (check log file(s) for error message)
    conda-env: /localhome/darwin/cbuckner/dna-seq-gatk-variant-calling/.snakemake/conda/6b8a95bbd3f6e08f9691577edcf026d4

RuleException:
CalledProcessError in line 13 of /localhome/darwin/cbuckner/dna-seq-gatk-variant-calling/workflow/rules/ref.smk:
Command 'source /localhome/darwin/anaconda3/bin/activate '/localhome/darwin/cbuckner/dna-seq-gatk-variant-calling/.snakemake/conda/6b8a95bbd3f6e08f9691577edcf026d4'; /localhome/darwin/anaconda3/envs/snakemake/bin/python3.9 /localhome/darwin/cbuckner/dna-seq-gatk-variant-calling/.snakemake/scripts/tmpcejz7p0d.wrapper.py' returned non-zero exit status 1.
  File "/localhome/darwin/cbuckner/dna-seq-gatk-variant-calling/workflow/rules/ref.smk", line 13, in __rule_get_genome
  File "/localhome/darwin/anaconda3/envs/snakemake/lib/python3.9/concurrent/futures/thread.py", line 52, in run
Traceback (most recent call last):
  File "/localhome/darwin/cbuckner/dna-seq-gatk-variant-calling/.snakemake/scripts/tmp72uissx8.wrapper.py", line 17, in <module>
    "vep_install --AUTO cf "
  File "/localhome/darwin/anaconda3/envs/snakemake/lib/python3.9/site-packages/snakemake/shell.py", line 263, in __new__
    raise sp.CalledProcessError(retcode, cmd)
subprocess.CalledProcessError: Command 'vep_install --AUTO cf --SPECIES homo_sapiens --ASSEMBLY GRCh38 --VERSION 98 --CACHEDIR resources/vep/cache --CONVERT --NO_UPDATE   > logs/vep/cache.log 2>&1' returned non-zero exit status 22.
[Fri Aug 13 12:46:46 2021]
Error in rule get_vep_cache:
    jobid: 10
    output: resources/vep/cache
    log: logs/vep/cache.log (check log file(s) for error message)
    conda-env: /localhome/darwin/cbuckner/dna-seq-gatk-variant-calling/.snakemake/conda/5fe2b2f099fb33a1161e354e3631910c

RuleException:
CalledProcessError in line 112 of /localhome/darwin/cbuckner/dna-seq-gatk-variant-calling/workflow/rules/ref.smk:
Command 'source /localhome/darwin/anaconda3/bin/activate '/localhome/darwin/cbuckner/dna-seq-gatk-variant-calling/.snakemake/conda/5fe2b2f099fb33a1161e354e3631910c'; python /localhome/darwin/cbuckner/dna-seq-gatk-variant-calling/.snakemake/scripts/tmp72uissx8.wrapper.py' returned non-zero exit status 1.
  File "/localhome/darwin/cbuckner/dna-seq-gatk-variant-calling/workflow/rules/ref.smk", line 112, in __rule_get_vep_cache
  File "/localhome/darwin/anaconda3/envs/snakemake/lib/python3.9/concurrent/futures/thread.py", line 52, in run
Removing output files of failed job get_vep_cache since they might be corrupted:
resources/vep/cache
```

**Comment by matviimykhailichenko** [comment]
Got kinda same problem. Have you solved it yet?

**Comment by tedil** [comment]
What do `logs/vep/cache.log` and `logs/get-genome.log` say?
